const widgetLines = [
  '(() => {',
  'const root=document.getElementById("cd-chat"); if(!root)return;',
  'const mode=root.dataset.mode||"floating",slug=root.dataset.slug||"",nome=root.dataset.nome||"o corretor";',
  'const state={step:1,intent:"",sub:""};',
  'const make=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};',
  'const clear=e=>{while(e.firstChild)e.removeChild(e.firstChild);};',
  'const panel=make("div",undefined,"cd-panel"),head=make("div",undefined,"cd-head"),avatar=make("div",nome.slice(0,2).toUpperCase(),"cd-avatar"),main=make("div",undefined,"cd-head-main"),counter=make("span","1 / 3","eyebrow"),bar=make("span"),body=make("div",undefined,"cd-body"),msg=make("div",undefined,"cd-message");msg.setAttribute("aria-live","polite");',
  'main.append(make("strong",nome),make("span","Normalmente responde em minutos","muted")); head.append(avatar,main,counter);',
  'const progress=make("div",undefined,"cd-progress");progress.append(bar);panel.append(head,progress,body);root.append(panel);if(mode!=="page")root.classList.add("cd-hidden");',
  'const close=()=>{if(mode!=="page")root.classList.add("cd-hidden");};',
  'if(mode!=="page"){const toggle=make("button","Abrir conversa","cd-toggle");toggle.type="button";toggle.setAttribute("aria-label","Abrir chat");toggle.addEventListener("click",()=>root.classList.remove("cd-hidden"));root.parentElement.append(toggle);const closeButton=make("button","Fechar","cd-close");closeButton.type="button";closeButton.setAttribute("aria-label","Fechar chat");closeButton.addEventListener("click",close);panel.append(closeButton);document.addEventListener("keydown",e=>{if(e.key==="Escape")close();});}',
  'const show=(text)=>{clear(msg);msg.textContent=text||"";};',
  'const option=(text,fn)=>{const b=make("button",text,"cd-option");b.type="button";b.addEventListener("click",fn);return b;};',
  'const render=()=>{clear(body);const h=make("h2",state.step===1?"Como podemos ajudar?":state.step===2?"Diga-nos um pouco mais":"Como podemos contactá-lo?");body.append(h);counter.textContent=state.step+" / 3";bar.style.width=(state.step*33.333)+"%";if(state.step===1)intentStep();else if(state.step===2)subStep();else formStep();body.append(msg);};',
  'const intentStep=()=>{const box=make("div",undefined,"cd-options");[["arrendamento","Arrendamento"],["compra_venda","Compra e venda"],["estudo_mercado","Estudo de mercado do imóvel"]].forEach(x=>box.append(option(x[1],()=>{state.intent=x[0];state.step=2;render();})));body.append(box);};',
  'const subStep=()=>{const box=make("div",undefined,"cd-options");if(state.intent==="estudo_mercado"){const label=make("label",undefined,"cd-form"),input=make("input");label.append(make("span","Zona ou morada do imóvel"),input);box.append(label,option("Continuar",()=>{state.sub=input.value.trim();if(state.sub.length<2)return show("Indique uma zona ou morada.");state.step=3;render();}));}else{const xs=state.intent==="arrendamento"?[["procuro_casa","Procuro casa"],["tenho_imovel","Tenho um imóvel"]]:[["comprar","Quero comprar"],["vender","Quero vender"]];xs.forEach(x=>box.append(option(x[1],()=>{state.sub=x[0];state.step=3;render();})));}body.append(box);};',
  'const formStep=()=>{const form=make("form",undefined,"cd-form");[["nome","Nome","text"],["email","E-mail","email"],["whatsapp","WhatsApp","tel"]].forEach(x=>{const l=make("label"),i=make("input"),error=make("span");l.dataset.field=x[0];error.className="cd-error";error.dataset.error=x[0];l.append(make("span",x[1]),i,error);i.name=x[0];i.type=x[2];i.required=true;if(x[0]==="whatsapp"){i.value="+351 ";i.inputMode="tel";}form.append(l);});const ml=make("label"),ta=make("textarea"),messageError=make("span");messageError.className="cd-error";messageError.dataset.error="mensagem";ml.append(make("span","Mensagem (opcional)"),ta,messageError);ta.name="mensagem";ta.maxLength=500;form.append(ml);const cl=make("label",undefined,"cd-consent"),cb=make("input"),consentError=make("span");cb.type="checkbox";cb.name="consent";consentError.className="cd-error";consentError.dataset.error="consent";cl.append(cb,make("span","Aceito que "+nome+" me contacte sobre este pedido."),consentError);form.append(cl);const hp=make("input");hp.name="hp";hp.tabIndex=-1;hp.autocomplete="off";hp.style.position="absolute";hp.style.left="-9999px";form.append(hp);const submit=make("button","Enviar pedido","cd-submit");submit.type="submit";form.append(submit);form.addEventListener("submit",e=>send(e,form,submit));body.append(form);};',
  'const send=async(e,form,submit)=>{e.preventDefault();show("");const data=Object.fromEntries(new FormData(form).entries());data.consent=form.elements.consent.checked;data.slug=slug;data.intencao=state.intent;data.sub_intencao=state.sub;data.utm={};new URLSearchParams(location.search).forEach((v,k)=>{if(["utm_source","utm_medium","utm_campaign","utm_content","utm_term"].includes(k))data.utm[k]=v;});submit.disabled=true;try{const r=await fetch("/c/api/lead",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)}),j=await r.json();if(!r.ok||!j.ok){Object.entries(j.erros||{}).forEach(x=>{const target=form.querySelector("[data-error="+x[0]+"]");if(target)target.textContent=x[1];});show("Corrija os campos indicados.");submit.disabled=false;return;}clear(body);body.append(make("h2","Pedido enviado"),make("div","Obrigado! "+j.nome_corretor+" vai contactá-lo em breve.","cd-message"));if(j.whatsapp_url){const a=make("a","Abrir WhatsApp");a.href=j.whatsapp_url;a.target="_blank";a.rel="noopener";body.append(a);}}catch(err){show("Não foi possível enviar agora. Tente novamente.");submit.disabled=false;}};',
  'render();',
  '})();',
];

export const CHAT_WIDGET_JS = widgetLines.join('\n');
