import { escapeAttr, escapeHtml, safeUrl } from '../lib/escape.js';

const CSS = [
  ':root{--bg:#0A0A0A;--surface:#141414;--surface-2:#1F1F1F;--line:#2A2A2A;--text:#E2E8F0;--muted:#9CA3AF;--amber:#D97706;--amber-bright:#F59E0B;--gold:#FCD34D;--mono:"JetBrains Mono",monospace}',
  '*{box-sizing:border-box}html{background:var(--bg)}body{margin:0;min-width:320px;background:radial-gradient(ellipse at 50% 0%,#1F1A12 0%,#0A0A0A 60%);color:var(--text);font-family:Inter,system-ui,sans-serif}',
  'a{color:var(--amber-bright);text-decoration:none}a:hover{color:var(--gold)}button,input,textarea{font:inherit}button{cursor:pointer}',
  '.page{width:min(100%,430px);min-height:100vh;margin:0 auto;padding:28px 22px 100px;display:flex;flex-direction:column;gap:22px}',
  '.physical-card{width:100%;aspect-ratio:346/216;padding:2px;border-radius:18px;background:linear-gradient(135deg,#FCD34D,#92400E 40%,#F59E0B 70%,#78350F);box-shadow:0 30px 60px rgba(0,0,0,.6),0 0 60px rgba(217,119,6,.2)}.physical-card-brand-row{display:flex;justify-content:space-between;align-items:flex-start}.physical-card-photo{width:56px;height:56px;border-radius:50%;object-fit:cover}',
  '.physical-card-inner{height:100%;padding:20px 22px;border-radius:16px;background:linear-gradient(160deg,#1C1C1C,#0B0B0B 60%,#161616);display:flex;flex-direction:column;justify-content:space-between}',
  '.brand,.eyebrow{font-family:var(--mono);letter-spacing:.14em}.brand{font-size:16px;font-weight:700;background:linear-gradient(90deg,#D97706,#FCD34D);-webkit-background-clip:text;background-clip:text;color:transparent}.card-name{font-size:clamp(22px,6vw,26px);font-weight:800;color:#fff}.card-role{font-family:var(--mono);font-size:11px;letter-spacing:.12em;color:var(--amber-bright)}',
  '.bio{font-size:15px;line-height:1.5;color:#D1D5DB}.eyebrow{font-size:11px;color:var(--muted)}.action-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.action-tile{min-height:78px;padding:14px 4px;background:var(--surface);border:1px solid var(--line);border-radius:14px;display:flex;align-items:center;justify-content:center;text-align:center;font-size:12px;font-weight:600;color:var(--text)}.action-tile:hover{border-color:var(--amber)}',
  '.services{display:flex;flex-wrap:wrap;gap:8px}.chip{padding:7px 10px;border:1px solid rgba(217,119,6,.45);border-radius:999px;color:var(--amber-bright);font-size:12px}.links-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.link-card{min-height:92px;padding:14px;background:linear-gradient(160deg,rgba(217,119,6,.22),#141414 70%);border:1px solid rgba(217,119,6,.45);border-radius:14px;display:flex;flex-direction:column;gap:8px}.link-card strong{color:#fff;line-height:1.2}.link-card span{font-size:12px;color:var(--muted);line-height:1.35}.contact-block{display:flex;flex-direction:column;gap:10px;padding:14px;background:var(--surface);border:1px solid var(--line);border-radius:14px}.social-row{display:flex;flex-wrap:wrap;gap:10px;font-size:13px}.footer{padding-top:6px;color:var(--muted);font-size:11px;line-height:1.6}.floating-cta{position:fixed;right:max(18px,calc((100vw - 430px)/2 + 18px));bottom:20px;min-height:52px;padding:0 18px;border:0;border-radius:999px;background:linear-gradient(135deg,#D97706,#F59E0B);box-shadow:0 10px 30px rgba(0,0,0,.5),0 0 30px rgba(217,119,6,.5);font-weight:800;color:#141414}.chat-page{min-height:100vh;padding:0}.chat-header{padding:18px 22px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center}.chat-header strong{color:#fff}.muted{color:var(--muted)}',
  '#cd-chat{font-size:14px}#cd-chat *{box-sizing:border-box}.cd-panel{background:var(--surface);border:1px solid rgba(217,119,6,.4);border-radius:22px;box-shadow:0 30px 80px rgba(0,0,0,.7),0 0 40px rgba(217,119,6,.15);overflow:hidden}.cd-floating{position:fixed;z-index:10;left:14px;right:14px;bottom:88px;max-width:402px;margin:auto}.cd-page{width:min(100%,430px);margin:0 auto;padding:20px 14px}.cd-head{display:flex;align-items:center;gap:12px;padding:14px 16px;border-bottom:1px solid var(--line)}.cd-avatar{width:40px;height:40px;border-radius:50%;background:var(--amber);display:flex;align-items:center;justify-content:center;font-weight:900;color:#141414}.cd-head-main{flex:1;display:flex;flex-direction:column;gap:2px}.cd-head-main strong{color:#fff}.cd-progress{height:3px;background:var(--line)}.cd-progress span{display:block;height:3px;background:var(--amber);transition:width .2s}.cd-body{padding:16px;display:flex;flex-direction:column;gap:12px}.cd-body h2{margin:0;font-size:18px;color:#fff}.cd-options{display:grid;gap:8px}.cd-option,.cd-submit,.cd-close{min-height:44px;border:1px solid var(--amber);border-radius:999px;background:transparent;color:var(--amber-bright);font-weight:700;padding:8px 14px}.cd-option:hover,.cd-option:focus-visible,.cd-submit:hover,.cd-submit:focus-visible{background:rgba(217,119,6,.18)}.cd-form{display:grid;gap:10px}.cd-form label{display:grid;gap:5px;color:var(--muted);font-size:12px}.cd-form input,.cd-form textarea{width:100%;padding:11px 12px;border:1px solid #333;border-radius:10px;background:#0D0D0D;color:#fff}.cd-form textarea{min-height:76px;resize:vertical}.cd-consent{display:flex!important;align-items:start;gap:8px}.cd-consent input{width:auto;margin-top:2px}.cd-error{color:#FCA5A5;font-size:12px}.cd-message{min-height:20px;color:var(--muted)}.cd-close{position:absolute;right:18px;bottom:18px;width:56px;padding:0;border:0;background:linear-gradient(135deg,#D97706,#F59E0B);color:#000}.cd-toggle{position:fixed;z-index:11;right:18px;bottom:20px;width:56px;height:56px;border:0;border-radius:50%;background:linear-gradient(135deg,#D97706,#F59E0B);box-shadow:0 10px 30px rgba(0,0,0,.5),0 0 30px rgba(217,119,6,.5);font-size:0}.cd-toggle:after{content:"+";font-size:28px;color:#000}.cd-hidden{display:none!important}@media(max-width:430px){.page{padding-left:16px;padding-right:16px}}',
].join('');

export function renderLayout({ title, description, canonicalPath, env, body }) {
  const base = String(env.PUBLIC_BASE_URL || '').replace(/\/$/, '');
  const canonical = base + canonicalPath;
  const image = safeUrl(body?.ogImage);
  const beacon = env.CF_BEACON_TOKEN
    ? '<script defer src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon=\'{"token":"' + escapeAttr(env.CF_BEACON_TOKEN) + '"}\'></script>'
    : '';
  return '<!doctype html><html lang="pt-PT"><head><meta charset="utf-8">'
    + '<meta name="viewport" content="width=device-width,initial-scale=1">'
    + '<title>' + escapeHtml(title) + '</title>'
    + '<meta name="description" content="' + escapeAttr(description) + '">'
    + '<meta property="og:title" content="' + escapeAttr(title) + '">'
    + '<meta property="og:description" content="' + escapeAttr(description) + '">'
    + (image ? '<meta property="og:image" content="' + escapeAttr(image) + '">' : '')
    + '<link rel="canonical" href="' + escapeAttr(canonical) + '">'
    + '<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>'
    + '<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&amp;family=JetBrains+Mono:wght@500;700&amp;display=swap">'
    + '<style>' + CSS + '</style>' + beacon + '</head><body>' + body.html + '</body></html>';
}
